name: Build and deploy Roll of Honour

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          ref: main 

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          global-json-file: ./global.json

      - name: Build with dotnet
        run: dotnet build ./RollOfHonour.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./RollOfHonour.sln --configuration Release --output ${{env.DOTNET_ROOT}}/myapp

      - name: Upload Build Artifact for deployment
        uses: actions/upload-artifact@v3.1.2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy_DEV:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'DEV'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3.0.2
        with:
          name: .net-app

      - name: Substitute appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: 'appsettings.json'
        env:
          ConnectionStrings.AzureAppConfiguration: ${{ secrets.APP_CONFIG_CONNECTION }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'APP-RollOfHonour-DEV-UKS'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_962F9BCB182E48269A190417EFBAC78B }}
          package: .          
          
  deploy_PRD:
    runs-on: windows-latest
    needs: [deploy_DEV]
    environment:
      name: 'PRD'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
          
      - name: Substitute appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: 'appsettings.json'
        env:
          ConnectionStrings.AzureAppConfiguration: ${{ secrets.APP_CONFIG_CONNECTION }}     

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'APP-RollOfHonour-PRD-UKS'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3E2EC3ECD1AC4FEE8D7F49648756DD4C }}
          package: .
